spring.application.name=NutriCard

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nutricard_db
spring.datasource.username=eka
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# USDA FoodData Central API
usda.api.key=${USDA_API_KEY:your_key_here}

# Springdoc / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
